### ISSUE TITLE
Deploy generates a lot of small files

### ISSUE THREAD

**Issue by klahnakoski** [mozilla-frontend-infra/codetribute#292]
Maybe deployment (for preview) would be faster if it did not generate 5K+ files

![image](https://user-images.githubusercontent.com/2334429/53576580-00465380-3b42-11e9-9bed-5d0f62b8b3a3.png)

**Comment by helfi92** [comment]
A project template file includes an icon property which allows a user to pick an icon from [materialdesignicons](https://materialdesignicons.com/) and include its name in the icon field of the yaml file. Because the icon is dynamically imported, webpack has to bundle all of the icons since it is only aware of the icon name at runtime. The import is being done [here](https://github.com/mozilla-frontend-infra/codetribute/blob/f1c06ffa5fbfe3a3947735ebf04bc812aa8c1662/src/components/ProjectCard/index.jsx#L56).
