### ISSUE TITLE
No LICENSE file in main repository

### ISSUE THREAD

**Issue by chtnnh** [mozilla-frontend-infra/codetribute#400]
Hello, I am a volunteer with the Wikimedia Foundation and we're planning to build something similar to what you folks have built here. We think it's a great solution. 

The front end stylesheets and javascript could be useful but there is no LICENSE document in the repository and I am unsure on how to proceed. Would be great if someone could look into it.

Thanks so much.

**Comment by djmitche** [comment]
Thanks for pointing that out!  This would be covered under the [Mozilla Public License v2](https://www.mozilla.org/en-US/MPL/2.0/).  I'll get a license file and other necessary metadata added.

**Comment by chtnnh** [comment]
Thank you so much. Great job on the website by the way!

**Comment by djmitche** [comment]
That's all @fiennyangeln :)

Do let us know how we can be helpful.  If it makes sense to "split" this into a generic portion and a Mozilla-specific portion (the data on our projects, for example), we'd be happy to work on that.

**Comment by chtnnh** [comment]
Wow that would be super helpful! Are you sure you would have the time for it?
It would help out immensely. Thank you so much

**Comment by djmitche** [comment]
I'd want to know it would be used, and make sure we build something that fits your needs, before getting started.  Let's start a new issue for that, and maybe you can give some detail on what that might look like -- perhaps the whole site is published as a React component?  Do you use GitHub?  Bugzilla?  Something else?  Depending on how challenging that turns out to be, we can figure out what kind of time is available.

**Comment by chtnnh** [comment]
The goal is to make it the one page that a new developer would visit to get started with contributing to Wikimedia, so yes I can assure you this tool will be used. Let me start another issue and we can continue the discussion there.
