### ISSUE TITLE
Help build similar website for Wikimedia foundation

### ISSUE THREAD

**Issue by chtnnh** [mozilla-frontend-infra/codetribute#401]
To answer the questions from https://github.com/mozilla-frontend-infra/codetribute/issues/400

1. We are thinking of building the site out and host it on Toolforge (https://wikitech.wikimedia.org/wiki/Portal:Toolforge) our internal hosting service for tools. This may change although.
2. GitHub is rarely used for issue tracking, its mostly Phabricator (https://phabricator.wikimedia.org). I can look into if an API or something similar exists that could help us out.

Please let me know if you have any follow up questions. Thank you once again for your time and support!

**Comment by djmitche** [comment]
Hosting on toolforge, from what I can see without signing in, looks appropriate -- the tool is entirely client-side, making all queries from the browser.

Currently Codetribute doesn't connect to Phabricator -- Mozilla only uses Phabricator for patch review (Dipherential), not for issue tracking (Maniphest).  So, I think that would need some development work on your part, including interfacing with the Maniphest API from the browser.  One thing that might make that tricky is CORS -- a browser fetching results from an origin of `https://codetribute.toolforge.org` might not be allowed by Maniphest's CORS protection (via headers like Access-Control-Allow-Origin).

The other tricky bits have to do with the code structure.

First, we've mixed configuration and code in this repository.  This is mostly limited to `src/data` and `images/projecticons`, so it should be relatively straightforward to break that apart.  The least difficult would probably be to make the entire site a single component that takes data and images as arguments, but perhaps you see a better way to break that up that would allow you the flexibility you need to customize other bits of the site.  For example, some of the built-in text about old bugs might not be appropriate for wikimedia.

Second, the Bugzilla and GitHub integrations are kind of "baked in".  In adding Maniphest, we could probably just bake it in the same way, but it might be better to try to break each backend out into its own module or package so that they can be maintained individually.

We can take some time to organize this work, and we can also look for help from other volunteers with React experience who might appreciate the chance to contribute and hone their skills.

**Comment by chtnnh** [comment]
The development work on our side will be taken care of. (Connecting to the Maniphest API)
I agree that the CORS might be tricky, I think thats a detail we will have to pay attention to.

Maybe I can fork this repository and go through the code to better understand the code structure. It would greatly help us break apart the code into what would help and what wouldn't. 

Would be glad to find volunteers to help out with this from the Wikimedia Foundation.

**Comment by aklapper** [comment]
Hi everyone, I'm Andre from the [Developer Advocacy team of the Wikimedia Foundation](https://www.mediawiki.org/wiki/Developer_Advocacy).

I'd like to add some background as the ticket summary (which I cannot correct) mentions "Wikimedia Foundation" (WMF) which feels a bit misleading. I welcome that @chtnnh volunteers (thank you!) to investigate a potential idea to improve developer onboarding in the Wikimedia movement. I'd just like to clarify that this ticket is not a request from the Wikimedia **Foundation** to our friends and allies at Mozilla.

Guiding new developer contributors to areas of their interest is a complex topic due to the complexity of Wikimedia's software ecosystem. My team is working on a better strategy for this which will still take us a while.

What is being proposed in this task might turn out to be a potential path to take, but (speaking for my team) we will first need more conversations and a clearer concept. It is also unclear how additional resources (like the one proposed in this ticket) would relate to existing Wikimedia resources (such as https://www.mediawiki.org/wiki/New_Developers and other places) when it comes to entry points for new contributors.

https://codetribute.mozilla.org/ is pretty awesome. If there is capacity to make its codebase more generic (split config and code; allow writing support for different backends; etc) and re-usable for other FLOSS projects and organizations out there that would certainly be great. Such work might welcome specific tasks with a clearer scope focused on codebase changes instead of focusing on potential "other users". Thanks a lot everyone! :)

**Comment by djmitche** [comment]
Understood, thanks!  We'd love to have more of those conversations about specific tasks, and who might do them most effectively.

**Comment by chtnnh** [comment]
Sorry for the confusion guys and thank you for clearing that up @aklapper 
@djmitche I have cloned the repo and am going through the code for now. I will try my best to get back to you at the earliest with what we can do to make this (codetribute) work for Wikimedia

**Comment by djmitche** [comment]
Closing this as a bit stale.  We're still happy to talk further about this!
